try{
	throw "AAA"
}catch(e){
	console.log("ERR:"+e);
}